# Generated by Django 4.2.1 on 2023-05-23 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0002_article_created_at_article_published_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="highlight",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="article",
            name="picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="article_pictures"
            ),
        ),
    ]
