# Generated by Django 4.2.1 on 2023-05-23 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0004_alter_article_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="picture",
            field=models.ImageField(
                default="media/article_pictures/unicorn.jpg",
                upload_to="media/article_pictures",
            ),
        ),
    ]
